<?xml version="1.0"?>
<robot name="pole2"
       xmlns:xi="http://www.w3.org/2001/XInclude"
       xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
       xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
       xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics">

  <property name="pole2_height" value="1.7" />
  <property name="pole2_width"  value="0.35" />
  <property name="pole2_depth"  value="0.35" />
  <property name="pole2_radius" value="0.02" />
  <property name="pole2_x"      value="0.0" />
  <property name="pole2_y"      value="0.0" />
  <property name="pole2_z"      value="0.0" />

  <property name="pole2_base_color" value="0 0 0 1" />
  <property name="pole2_color" value="0 0 0 1" />

  <property name="pole2_base_thickness" value="0.05"/>

  <property name="M_PI" value="3.1415926535897931" />


  <link name="pole2_base_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="${pole2_x} ${pole2_y} ${pole2_z}" />
      <inertia ixx="1" ixy="0"  ixz="0"
               iyy="1" iyz="0"
               izz="1" />
    </inertial> 
    <visual>
      <origin xyz="${pole2_x} ${pole2_y} ${pole2_z}" />
      <geometry>
        <box size="${pole2_width} ${pole2_depth} ${pole2_base_thickness}" />
      </geometry>
      <material name="pole2_base_blue">
        <color rgba="${pole2_base_color}"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="${pole2_x} ${pole2_y} ${pole2_z}" />
      <geometry>
        <box size="${pole2_width} ${pole2_depth} ${pole2_base_thickness}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="pole2_base_link">
    <material>Gazebo/LightWood</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <joint name="pole2_joint" type="fixed" >
    <parent link="pole2_base_link" />
    <origin xyz="0 0 ${pole2_base_thickness}" rpy="0 0 0" />
    <child link="pole2_link" />
  </joint> 
  <link name="pole2_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 ${-pole2_height/2}" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${+pole2_height/2-pole2_base_thickness}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${pole2_radius}" length="${pole2_height-pole2_base_thickness}" />
      </geometry>
      <material name="pole2_blue">
        <color rgba="${pole2_color}"/>
      </material>
    </visual> 

    <collision>
      <origin xyz="0.0 0.0 ${+pole2_height/2-pole2_base_thickness}" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${pole2_radius}" length="${pole2_height-pole2_base_thickness}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="pole2_link">
    <material>Gazebo/Gray</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>


  <joint name="pole2_top" type="fixed" >
    <parent link="pole2_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
    <child link="pole2_top_link" />
  </joint> 
  <link name="pole2_top_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 -0.1 ${pole2_height-pole2_base_thickness - 0.01}" rpy="1.56 0 0" />
      <geometry>
        <cylinder radius="${pole2_radius }" length="0.75" />
      </geometry>
      <material name="pole2_blue">
        <color rgba="128 128 128 1"/>
      </material>
    </visual> 

    <collision>
      <origin xyz="0.0 -0.1 ${pole2_height-pole2_base_thickness - 0.01}" rpy="1.56 0 0" />
      <geometry>
        <cylinder radius="${pole2_radius }" length="0.75" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="pole2_top_link">
    <material>Gazebo/Gray</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>
 
  <joint name="kinect_pole" type="fixed" >
    <parent link="pole2_top_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
    <child link="kinect_pole_link" />
  </joint> 
  <link name="kinect_pole_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 -0.5 ${pole2_height-pole2_base_thickness - 0.01}" rpy="-0.15 0 0" />
      <geometry>
        <box size="0.25 0.07 0.08" />
      </geometry>
      <material name="pole2_blue">
        <color rgba="128 128 128 1"/>
      </material>
    </visual> 

    <collision>
      <origin xyz="0.0 -0.5 ${pole2_height-pole2_base_thickness - 0.01}" rpy="-0.15 0 0" />
      <geometry>
        <box size="0.25 0.07 0.08" />
      </geometry>    
    </collision>
  </link>
  <gazebo reference="kinect_pole_link">
    <material>Gazebo/Gray</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>


<joint name="op_table" type="fixed" >
    <parent link="pole2_base_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />
    <child link="op_table_link" />
  </joint> 
  <link name="op_table_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.1" ixy="0"  ixz="0"
               iyy="0.1" iyz="0"
               izz="0.01" />
    </inertial> 
    <visual>
      <origin xyz="0.0 -0.62 0.74" rpy="0 0 0" />
      <geometry>
        <box size="0.75 0.56 0.03" />
      </geometry>
      <material name="pole2_blue">
        <color rgba="0 0 0 1"/>
      </material>
    </visual> 

    <collision>
      <origin xyz="0.0 -0.62 0.74" rpy="0 0 0" />
      <geometry>
        <box size="0.75 0.56 0.02" />
      </geometry>    
    </collision>
  </link>
  <gazebo reference="op_table_link">
    <material>Gazebo/Gray</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>



</robot>
